### ISSUE TITLE
Doesn't work with d3 on observable

### ISSUE THREAD

**Issue by RandomFractals** [uwdata/gemini#2]
see: https://observablehq.com/@randomfractals/hello-gemini

& https://observablehq.com/@d3/d3v6-migration-guide#group

**Comment by yhoonkim** [comment]
@RandomFractals I've updated the code to use d3.v6's `groups` instead of `nest`. Let me know if it does not work. 
Thanks!!

**Comment by yhoonkim** [comment]
https://observablehq.com/@yhoonkim01/hello-gemini
It seems to work!
