### ISSUE TITLE
Supports multiple plays?

### ISSUE THREAD

**Issue by GCheung55** [uwdata/gemini#3]
Does Gemini support multiple plays? For example if there is a visualization that has already transitioned to an end spec once, can that same visualization transition to another end spec?

**Comment by yhoonkim** [comment]
Umm, that's actually what I'm working on it as my next project.

For now:

Let's say there are three visualization specs (A, B, C) and two transitions T1(A->B), T2(B->C).
After T1, the visualization at the target div container may not be animated right away by applying T2 animation. Though, you can do the same thing by embedding B visualization after T1 then applying T2. 

Here is an example:
```js
async function play(i) {
  let target = "#anim",
    anim = globalThis.anims[i];

  await vegaEmbed(target, anim.rawInfo.sVis.spec, {renderer: "svg", actions: false});
  await anim.play(target)
}
async function playAll() {
  for (let i = 0; i < globalThis.anims.length; i++) {
    await play(i)
  }
}
```
