### ISSUE TITLE
Support Vega spec?

### ISSUE THREAD

**Issue by GCheung55** [uwdata/gemini#4]
Current API seems to only support Vega-Lite specs. Can Vega.js specs be supported too?

**Comment by yhoonkim** [comment]
It supports vega specs :)

Though, Gemini needs to know the names of the components.
- `mark` component's name can be set on `name`.
- `axis` component's name can be set on `"encode": {"axis": {"name": "__name__"}}`.
- `legend` component's name can be set on `"encode": {"legend": {"name": "__name__"}}`.

It's a bit weird but this is how currently Vega names the component on svg rendering...

**Comment by yhoonkim** [comment]
I'll make a wiki page and link to this page on the readme.md to clarify this. Thanks!

**Comment by GCheung55** [comment]
I don't think Vega specs are exactly supported because the methods are not exposed.

The `vl2vg4gemini` method takes a Vega-Lite spec, but there isn't a method that takes a Vega spec.

It would be helpful to have a method like the `vl2vg4gemini` method that does:

```
export function vg4gemini(vgSpec) {
  vgSpec.axes = mergeDuplicatedAxes(vgSpec.axes);
  appendNamesOnGuides(vgSpec);
  return vgSpec;
}
```

**Comment by yhoonkim** [comment]
@GCheung55 
Gemini supports the single-view Vega specs, which are legal Vega spec but only have one or less axis for x and y and name properties on each component. 

The single-view Vega specs having names on their components do not need to be processed by the functions. 

`vg4gemini` seems a good idea for better UX :)
