### ISSUE TITLE
Too large font in end animation

### ISSUE THREAD

**Issue by joelostblom** [uwdata/gemini#9]
This project is really cool! I would like to make some animations to explain how plots are made to my students, but I noticed that the font gets really large in the end stage of the animation although it is the standard size in the start and end VL spec.

![image](https://user-images.githubusercontent.com/4560057/121051772-98decb80-c76e-11eb-8d54-964cd46df251.png)

**Comment by yhoonkim** [comment]
Thank you for catching this! Can I ask what was the web browser (with version) you tested?

**Comment by joelostblom** [comment]
In Firefox 88 on Ubuntu 20.10. I just tested in chromium 83 and there everything looks like I would expect.

**Comment by yhoonkim** [comment]
Thanks for the info. I will look into this issue when I get some time. Feel free to upload PR :)

**Comment by yhoonkim** [comment]
I fixed it in the last commit by testing at Firefox on MacOS.

**Comment by joelostblom** [comment]
Great! Thank you for the quick fix!
